# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- Dev

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: '-list'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: 'superdeker.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, 11, default, specifyPath
